// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8l4XrI1yMWWPkSz8xvGY7eRvvnqc0RKc',
    appId: '1:935381746988:web:57ca9b4e82bffa52afd889',
    messagingSenderId: '935381746988',
    projectId: 'fridge-feast-al7kv',
    authDomain: 'fridge-feast-al7kv.firebaseapp.com',
    storageBucket: 'fridge-feast-al7kv.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXZClTK_Nqj5FJjYyaxYiiiF5GoGKe80I',
    appId: '1:935381746988:android:6023b04fd6615aebafd889',
    messagingSenderId: '935381746988',
    projectId: 'fridge-feast-al7kv',
    storageBucket: 'fridge-feast-al7kv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhohBFJEfsenuXhbJfe9zaDbIa-sbKLHA',
    appId: '1:935381746988:ios:92fc310d583ae24bafd889',
    messagingSenderId: '935381746988',
    projectId: 'fridge-feast-al7kv',
    storageBucket: 'fridge-feast-al7kv.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhohBFJEfsenuXhbJfe9zaDbIa-sbKLHA',
    appId: '1:935381746988:ios:92fc310d583ae24bafd889',
    messagingSenderId: '935381746988',
    projectId: 'fridge-feast-al7kv',
    storageBucket: 'fridge-feast-al7kv.firebasestorage.app',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8l4XrI1yMWWPkSz8xvGY7eRvvnqc0RKc',
    appId: '1:935381746988:web:83dd50d50d9b565dafd889',
    messagingSenderId: '935381746988',
    projectId: 'fridge-feast-al7kv',
    authDomain: 'fridge-feast-al7kv.firebaseapp.com',
    storageBucket: 'fridge-feast-al7kv.firebasestorage.app',
  );
}
